name: Show Hasnode Blog Posts on Readme
on:
  schedule:
    # Runs every 6 hours of the day
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read blog RSS feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOGPOSTS"
          feed_list: "https://blog.equationlabs.io/rss.xml"
          template: "$newline - $randomEmoji(💯,🔥,💫,🚀,🌮) [$title]($url)"
          max_post_count: 7
          commit_message: "recent posts section updated"
          readme_path: ./profile/README.md
          gh_token: ${{ secrets.GITHUB_TOKEN }}
